### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jbesta** [rictorres/node-rpm-builder#19]
Latest repository version contains support for RPM `Provides` parameter. Latest published version on npm registry is, however, 0.6.1 - according to https://www.npmjs.com/package/rpm-builder

**Comment by jbesta** [comment]
@rictorres There was no release since Apr, 2015. Project codebase now contains few new features - support for `provides`, `packager` and `changelog` options - which might be helpful. Do you plan to release new version of package to npm?

**Comment by rictorres** [comment]
Yep, I'll do that later today :)
Thanks a lot 👍

**Comment by jbesta** [comment]
@rictorres any news on that topic?

**Comment by jbesta** [comment]
@rictorres 
Hi again after a while 😄.
Latest released version is still `0.6.1` according to https://www.npmjs.com/package/rpm-builder
Will you release new version to npm?

If you're short short on time, I'm willing to provide maintenance support for the project 😄

**Comment by rictorres** [comment]
hey, @jbesta 
thanks a lot for reaching out again. yes, i'd love your help with the project.

**Comment by rictorres** [comment]
cc @jbesta ☺️

**Comment by jbesta** [comment]
Hi after a while.

Thanks for your invitation. Everything works fine.
I've created release [v0.7.0](https://github.com/rictorres/node-rpm-builder/releases/tag/v0.7.0)

@rictorres Could you publish this version to npm registry?

**Comment by rictorres** [comment]
done!

apologies once again for the delay (i was on vacation)

**Comment by jbesta** [comment]
Thanks a lot 👍.

I hope you've enjoyed your vacation 😄
